### ISSUE TITLE
mock untyped parameters

### ISSUE THREAD

**Issue by ivyhjk** [usox/hackmock#1]
some classes are already written in PHP, and when their have some untyped parameters, mocking fails, for example:

```
<?hh // decl

class Foo {
  public function untypedParameter($param): void { 

  }
}
```

also works with `<?php` as initial tag.

The error:

```
Fatal error: A type specifier is expected here. in /app/vendor/usox/hackmock/src/Mock.hh(123)(df9b58dfc07696f2f66f85fd021ce9e7) : eval()'d code on line 5
```

I know that PHP support is ending for HHVM, but come on, this is breaking a lot of possible mocks and possible integrations with this great library.

**Comment by usox** [comment]
I think, I'm ok with it. I actually don't remember, why I had to add the leading `?` in the first place. After performing some tests with some of my projects, it indeed seems to be unnecessary.

**Comment by usox** [comment]
Thanks!
